export default {
    PUSH_STATE: 'PUSH_STATE',
    UPDATE_BREWERIES_FILTER: 'UPDATE_BREWERIES_FILTER',
    UPDATE_BEERS_FILTER: 'UPDATE_BEERS_FILTER',
    async: {
        FETCH_BREWERIES_REQUEST: 'FETCH_BREWERIES_REQUEST',
        FETCH_BREWERIES_SUCCESS: 'FETCH_BREWERIES_SUCCESS',
        FETCH_BREWERIES_FAILURE: 'FETCH_BREWERIES_FAILURE',
        RECEIVE_BEERS: 'RECEIVE_BEERS'
    }
}